name = "proveedores-proveedor"
compatibility_date = "2026-03-24"
pages_build_output_dir = "./public"

[vars]
APPS_SCRIPT_PROVIDER_API_URL = "https://script.google.com/macros/s/AKfycbx_Yt5TX8Fmq2-s2J9lnCZiT78GLeE9zf5zpua442RM1Ro_dlY76RW5-G-iWU8T787K/exec"
